### PR TITLE
Game Carousel on Main Page

### PR DESCRIPTION
**Pull request by sayus2884**

### CODE REVIEW

**Comment by sayus2884** [comment]
[Game Carousel (Main)](https://trello.com/c/aBO3utNJ/39-game-carousel-main)

**Review by hulyak — APPROVED** [review]
This looks very good, I didn't know about react responsive carousel library. For the modal, we can use createPortal from React library. I have been trying to implement for getting in touch form. Or [Next.js](https://github.com/vercel/next.js/tree/canary/examples/with-route-as-modal) has an example component for creating a modal. Do you think we can use it? 

One more thing, I'm getting a warning in the console. Did you notice?  @sayus2884 

No images found! Can't build the thumb list without images. If you don't need thumbs, set showThumbs={false} in the Carousel. Note that it's not possible to get images rendered inside custom components. More info at https://github.com/leandrowd/react-responsive-carousel/blob/master/TROUBLESHOOTING.md

**Comment by sayus2884** [comment]
@hulyak Will look into the warnings before the merge. 

I haven't tried createPortal, but I'm reading that it's commonly used for modals, so I think it's good practice to use it for the getting in touch form since it's acting like a popup modal according to the design specs. I just don't know how the animation is coded though.

**Comment by hulyak** [comment]
> @hulyak Will look into the warnings before the merge.
> 
> I haven't tried createPortal, but I'm reading that it's commonly used for modals, so I think it's good practice to use it for the getting in touch form since it's acting like a popup modal according to the design specs. I just don't know how the animation is coded though.

You can check out this example for [transition.](https://codesandbox.io/s/13jozn2wr7?file=/src/DropdownItem.js) It looks cool. 😅. Yeah, generally `createPortal` is used for modals. Another example is also very good, you can check out this [video](https://www.youtube.com/watch?v=EyjuRCxpf6Y&t=12s&ab_channel=LeighHalliday). @sayus2884

**Comment by sayus2884** [comment]
@hulyak  Aye. Will definitely revisit the services section. React-collapse looks like a better implementation since it already has the animation and other options. 

The video is also helpful. I'm planning on working on the game info modal next.

Thanks, this was a good find!

**Review by Muddoo — CHANGES_REQUESTED** [review]
I really like your work on this component and lib you used 

some fixed i need to merge the component 

1. use next/image
2. set interval to 2500
3. set transitionTime 700

image

**Pull request merged**
